<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.10">
  <POU Name="STRING_BUFFER" Id="{374b3c54-560a-41fa-bda9-0812129e1bc7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK STRING_BUFFER
VAR CONSTANT
	iBufferLength : UINT := 50;
END_VAR
VAR_INPUT
	
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="STRING_BUFFER">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>